### ISSUE TITLE
Link tagline (comments, share, hide, etc) is missing on compressed mode

### ISSUE THREAD

**Issue by RoryStolzenberg** [Axel--/Naut-for-reddit#53]
Bug introduced in 4.0 release. Looks like this:

![Missing tagline image](http://i.imgur.com/Xo9Nj1x.png)

Pull request forthcoming.

**Comment by RoryStolzenberg** [comment]
Fixed to expected behavior:

~[Fixed tagline](http://i.imgur.com/v5PeO52.png)

**Comment by mplewis** [comment]
Hello @Axel--, this issue is still affecting me. Will this PR work?

**Comment by RenegadeAI** [comment]
Is this an issue with compressed mode?

**Comment by RoryStolzenberg** [comment]
@RenegadeAI: Correct. Fix also only affects compressed mode, since it's a CSS property on `.link.compressed`.
